#DB SETTING
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.152.79.226:13306/zicdding_class?serverTimezone=Asia/Seoul
    username: root
    password: zicdding
  mail:
    host: smtp.co.kr
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    context-path: /api/v1

server:
  port: 8081
  web:
      resources:
        favicon:
          enabled=false:

  jpa:
    open-in-view: false

  thymeleaf:
    check-template-location: false



logging:
  file:
    path:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: swagger-ui.html

jwt:
  secret: fdbefdd5f5f35f1ad4e903c6abe29ec8488e0ec0b8e2da402733611ed9c4a612
  access-token-expiration: 3600000000000000
  refresh-token-expiration: 259200
  issuer: zicdding


minio:
  url: http://121.152.79.226:19001        # MinIO 서버 URL
  access-key: minio              # MinIO 액세스 키
  secret-key: miniopass              # MinIO 시크릿 키
  bucket-name: users   # 버킷 이름