#DB SETTING
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.152.79.226:13306/zicdding_class?serverTimezone=Asia/Seoul
    username: root
    password: zicdding
  mail:
    host: smtp.co.kr
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081



# Logging

logging:
  file:
    path:
  level:
    root: INFO

# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE
# logging.level.org.springframework.jdbc.core = TRACE


springdoc:
  swagger-ui:
    path: swagger-ui.html

jwt:
  secret: fdbefdd5f5f35f1ad4e903c6abe29ec8488e0ec0b8e2da402733611ed9c4a612
  access-token-expiration: 3600 # 1??
  refresh-token-expiration: 259200 # 3?
  issuer: your_application